spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gem_prep
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080